### ISSUE TITLE
Current instructions to execute the basic demo not working.

### ISSUE THREAD

**Issue by KaruroChori** [Rolands-Laucis/Socio#15]
`npm run demo ` is not available, only dev & test.
And at the moment the library is not properly mapped in the client code, so the full path is required:
`import { SocioClient } from './node_modules/socio/dist/core-client.js'`

in place of `'./core-client.js'`

**Comment by KaruroChori** [comment]
Actually, the entire code for the basic demo seems to be not aligned with the current code in the repository. sc.query for example is used in place of sc.Query.

**Comment by Rolands-Laucis** [comment]
Thanks 👍. I didnt realize that the basic demo was that far behind on Socio versions 😅. Fixed this in commit 78e288efd7bcbde7d71490d7824ab9f1159c1fa1 and the demo was updated to Socio v0.7.12. Should be all good now, but i had to do some funky stuff for base64.js to work 🤔
