### ISSUE TITLE
NoSQL

### ISSUE THREAD

**Issue by grantsavill** [Rolands-Laucis/Socio#17]
Looking to use this project with server props only, however, the DB object on SocioServer seems to be mandatory? Is there a way around this?

**Comment by Rolands-Laucis** [comment]
Sorry, just noticed this now😅As of v1.9.0 the db.Query field is optional. I used to just pass ()=>{} in it for testing, but now you can just supply db:{} without any fields 👌 
Check [DB init docs](https://github.com/Rolands-Laucis/Socio/blob/main/Documentation.md#db-init-object-database-query-arbiter-allowed-verbs) for more info
